layout_spectrum: 0.9260651
color:
  saturation: 0.7349624
  lightness: 1
  brandStrength: 0.9962406
  brandColors:
    - '#0D0E16'
    - '#6E6664'
    - '#FFFAE0'
    - '#DEB677'
    - '#EA1E39'
  rhythmicContrast: 1
typography_spectrum: 0.518797
name: CHUNKY STYLE MUSIC
